# Generated by Django 5.2.15 on 2026-06-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('code', models.CharField(db_column='code', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='code_nm', max_length=100)),
                ('remarks', models.CharField(blank=True, db_column='rmrk_cn', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code',
                'verbose_name_plural': 'codes',
                'db_table': 'tbl_code',
            },
        ),
    ]
