# Generated by Django 5.2.15 on 2026-06-22 06:36

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(db_column='crt_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_column='mdfcn_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('sn', models.AutoField(db_column='docs_sn', primary_key=True, serialize=False)),
                ('version', models.CharField(db_column='docs_ver', max_length=20)),
                ('modification_content', models.CharField(db_column='mdfcn_cn', max_length=100)),
                ('created_by', models.ForeignKey(db_column='creatr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(db_column='docs_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='common.code')),
                ('possession_user', models.ForeignKey(blank=True, db_column='pssn_user_sn', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occupied_documents', to=settings.AUTH_USER_MODEL)),
                ('progress_status', models.ForeignKey(db_column='docs_prgrs_stts_cd', db_constraint=False, default='PRGRS_PENDING', on_delete=django.db.models.deletion.PROTECT, related_name='documents_by_progress', to='common.code')),
                ('project', models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.project')),
                ('updated_by', models.ForeignKey(db_column='mdfr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'tbl_docs',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('created_at', models.DateTimeField(db_column='crt_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='del_yn', default='N', max_length=1)),
                ('sn', models.AutoField(db_column='docs_dtl_sn', primary_key=True, serialize=False)),
                ('detail_content', models.BinaryField(blank=True, db_column='docs_dtl_cn', null=True)),
                ('path', models.CharField(db_column='docs_path', max_length=300)),
                ('created_by', models.ForeignKey(db_column='creatr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_column='docs_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='docs.document')),
            ],
            options={
                'verbose_name': 'document detail',
                'verbose_name_plural': 'document details',
                'db_table': 'tbl_docs_detail',
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('created_at', models.DateTimeField(db_column='crt_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_column='mdfcn_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('approval_sn', models.AutoField(db_column='docs_aprv_sn', primary_key=True, serialize=False)),
                ('request_content', models.CharField(db_column='dmnd_cn', max_length=100)),
                ('rejection_reason', models.CharField(blank=True, db_column='rjct_rsn', max_length=100, null=True)),
                ('approval_status', models.ForeignKey(db_column='aprv_stts_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to='common.code')),
                ('created_by', models.ForeignKey(db_column='creatr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='mdfr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(db_column='docs_dtl_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='docs.documentdetail')),
            ],
            options={
                'verbose_name': 'document approval',
                'verbose_name_plural': 'document approvals',
                'db_table': 'tbl_docs_approve',
            },
        ),
    ]
