# Generated by Django 5.2.15 on 2026-06-22 06:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('created_at', models.DateTimeField(db_column='crt_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_column='mdfcn_dt', db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('sn', models.AutoField(db_column='file_sn', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='file_nm', max_length=100)),
                ('path', models.CharField(db_column='file_path', max_length=300)),
                ('size', models.IntegerField(db_column='file_size')),
                ('extension', models.CharField(db_column='file_ext', max_length=4)),
                ('created_by', models.ForeignKey(db_column='creatr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.ForeignKey(db_column='file_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='project_files', to='common.code')),
                ('project', models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='projects.project')),
                ('updated_by', models.ForeignKey(db_column='mdfr_sn', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project file',
                'verbose_name_plural': 'project files',
                'db_table': 'tbl_file',
            },
        ),
    ]
